import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      padding: 20,
      backgroundColor: "#fff",
      borderRadius: 10,
      elevation: 3,
      shadowColor: "#000",
      shadowOpacity: 0.5,
      shadowRadius: 9,
      shadowOffset: { width: 0, height: 2 },
    },
    toggleContainer: {
      flexDirection: "row",
      backgroundColor: "#F5F5F5",
      borderRadius: 8,
      marginBottom: 15,
      alignContent: "center",
      justifyContent: "center",
      height: 45,
    },
    toggleButton: {
      flex: 1,
      alignItems: "center",
      borderRadius: 8,
      overflow: "hidden",
    },
    background: {
      position: "absolute",
      width: "100%",
      height: "100%",
      borderRadius: 12,
      backgroundColor: "#F0F0F0",
    },
    activeBackground: {
      position: "absolute",
      width: "50%",
      height: "100%",
      backgroundColor: "#C56E33",
      borderRadius: 14,
    },
    buttonContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      paddingHorizontal: 20,
      alignItems: "center",
      height: 40,
    },
    toggleText: {
      marginTop: 5,
      fontSize: 18,
      color: "#2F2D2C",
    },
    activeText: {
      color: "#fff",
      fontWeight: "bold",
    },
    addressContainer: {
      marginBottom: 10,
      marginTop: 5,
      paddingLeft: 9,
    },
    title: {
      fontSize: 25,
      fontWeight: "bold",
      color: "#2F2D2C",
      marginBottom: 6,
    },
    addressTitle: {
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 14,
      color: "#303336",
    },
    addressDetails: {
      fontSize: 16,
      color: "#666",
    },
    coordinates: {
      fontSize: 14,
      color: "#888",
      marginTop: 5,
    },
    buttonContainer: {
      flexDirection: "row",
    },
    actionButton: {
      flexDirection: "row",
      backgroundColor: "white",
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderColor: "#DEDEDE",
      borderWidth: 2,
      paddingRight: 21,
      marginLeft: 8,
      marginRight: 8,
      borderRadius: 20,
    },
    buttonText: {
      fontSize: 14,
    },
    buttonTexts: {
        fontSize: 14,
        color:"white",
      },
    modalContainer: {
      marginTop: 210,
      padding: 20,
      backgroundColor: "white",
      borderRadius: 10,
      marginHorizontal: 20,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 5,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 10,
    },
    input: {
      borderWidth: 1,
      padding: 10,
      marginTop: 10,
      borderRadius: 5,
      borderColor: "#ccc",
    },
    saveButton: {
      backgroundColor: "#C56E33",
      padding: 10,
      marginTop: 15,
      alignItems: "center",
      borderRadius: 5,
    },
  });
  